FROM node:22.17.1

WORKDIR /app

# Copy package.json only first
COPY package.json ./

# Install dependencies **inside container**
RUN npm install

# Copy rest of the code
COPY . .

EXPOSE 5173

# Vite dev with host + force rebuild
CMD ["npm", "run", "dev", "--", "--host", "--force"]
