# Dockerfile for the API service
FROM node:22.17.1

WORKDIR /app

# Copy package files first
COPY package*.json ./

RUN npm install

# Copy rest of the backend code
COPY . .

EXPOSE 5000

# For development with nodemon
CMD ["npx", "nodemon", "index.js"]
