export const dummyData = {
  user: {
    id: 'user_12345',
    username: 'JaneDoe',
    profilePic: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3',
    bio: 'An avid writer sharing my thoughts on life, tech, and travel.',
  },
  posts: [
    {
      id: 'post_1',
      title: 'My First Journey into React',
      author: 'JaneDoe',
      authorId: 'user_12345',
      date: '2025-09-24',
      image: 'https://images.unsplash.com/photo-1617529497471-9218633199c0?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
      content: 'I recently started learning React and it has been an amazing experience. The component-based architecture makes building UIs so much more intuitive. I highly recommend it for anyone interested in web development.',
      likes: 15,
      comments: [
        { id: 'comment_1', author: 'JohnSmith', text: 'Great post! I love React too.' },
        { id: 'comment_2', author: 'AliceDoe', text: 'Super helpful, thanks for sharing!' },
      ],
      tags: ['React', 'Web Development', 'Programming'],
    },
    
    {
      id: 'post_2',
      title: 'A Beginners Guide to UX Design',
      author: 'JaneDoe',
      authorId: 'user_12345',
      date: '2025-09-18',
      image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
      content: 'User Experience (UX) design is about creating products that provide meaningful and relevant experiences to users. Learn the basic principles and tools to get started in this exciting field.',
      likes: 31,
      comments: [],
      tags: ['Design', 'UX', 'Technology'],
    },
    {
      id: 'post_3',
      title: 'Tips for Hiking in the Wilderness',
      author: 'JaneDoe',
      authorId: 'user_12345',
      date: '2025-09-15',
      image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=2070&auto=format&fit=crop',
      content: 'Whether you\'re a seasoned hiker or just starting out, preparing for a trip into the wilderness is key. This post covers essential gear, safety tips, and trail etiquette.',
      likes: 58,
      comments: [
        { id: 'comment_4', author: 'AlexHiker', text: 'Great advice! I never thought about bringing an emergency whistle.' },
      ],
      tags: ['Hiking', 'Outdoors', 'Adventure'],
    },
    {
      id: 'post_4',
      title: 'Photography Tips for Beginners',
      author: 'JaneDoe',
      authorId: 'user_12345',
      date: '2025-09-05',
      image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop',
      content: 'Want to take better photos? These tips cover composition, lighting, and editing to help you capture stunning images.',
      likes: 29,
      comments: [],
      tags: ['Photography', 'Tips', 'Creativity'],
    },
    {
      id: 'post_5',
      title: 'Top 10 Books That Changed My Life',
      author: 'JaneDoe',
      authorId: 'user_12345',
      date: '2025-09-02',
      image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=2070&auto=format&fit=crop',
      content: 'Books have the power to transform perspectives. Here are ten books that had a profound impact on my thinking and personal growth.',
      likes: 38,
      comments: [
        { id: 'comment_6', author: 'BookLover', text: 'Adding these to my reading list!' },
      ],
      tags: ['Books', 'Education', 'Lifestyle'],
    },
  ],
  trendingTags: ['React', 'Travel', 'Health', 'Programming', 'Lifestyle', 'Design', 'Hiking', 'Running', 'Photography', 'DIY'],
};
